version: 2.1

executors:
  windows-executor:
    docker:
      - image: cimg/python:3.12.5
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            .\venv\Scripts\activate
            pip install -r requirements.txt

  test:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Run Playwright tests with pytest
          command: |
            .\venv\Scripts\activate
            pytest --maxfail=1 --disable-warnings -q

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
