version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.12.5-slim
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  run_tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run Playwright setup
          command: |
            . venv/bin/activate
            pip install playwright
            python -m playwright install
      - run:
          name: Run pytest with Allure results
          command: |
            . venv/bin/activate
            pip install allure-pytest
            pytest --alluredir=allure-results

  upload_allure_report:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Allure CLI dependencies
          command: |
            apt-get update && apt-get install -y \
              curl \
              jq \
              wget \
              unzip
      - run:
          name: Install Allure CLI
          command: |
            curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest \
              | jq -r '.assets[] | select(.name | test("allure-commandline.*\\.zip$")) | .browser_download_url' \
              | xargs wget -qO allure.zip
            unzip allure.zip -d allure
            export PATH=$PATH:$(pwd)/allure/bin
      - run:
          name: Generate Allure report
          command: allure serve allure-results
      - store_artifacts:
          path: allure-results  # Store Allure results as artifacts
          destination: allure-results

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - upload_allure_report:
          requires:
            - run_tests
