name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright
          pip install allure-pytest

      - name: Install specific version of Google Chrome (131.0.6778.70)
        run: |
          $chrome_version = "131.0.6778.70"
          $chrome_installer_url = "https://dl.google.com/release2/chrome/${chrome_version}/chrome_installer.exe"
          Invoke-WebRequest -Uri $chrome_installer_url -OutFile "$env:USERPROFILE\chrome_installer.exe"
          Start-Process -FilePath "$env:USERPROFILE\chrome_installer.exe" -ArgumentList "/silent", "/install" -Wait

      - name: Install Playwright dependencies
        run: |
          python -m playwright install --with-deps

      - name: Run tests
        run: |
          pytest -v -s

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
