name: Tests                                              # The name of the workflow

on:
  - push                                                 # Trigger the workflow whenever code is pushed to the repository

jobs:
  test:
    runs-on: windows-latest                              # Runs the job on the latest available Windows environment (Windows Server 2022)

    steps:
      - uses: actions/checkout@v3                        # Checkout the code from the repository so the workflow can use it

      - name: Setup Python                               # Set up the specified version of Python
        uses: actions/setup-python@v4                    # GitHub's official action for setting up Python
        with:
          python-version: '3.12.5'                       # Specify the Python version to use (3.12.5)

      - name: Install dependencies                       # Install all the required dependencies listed in requirements.txt
        run: |
          python -m pip install --upgrade pip            # Upgrade pip to the latest version
          pip install -r requirements.txt                # Install all dependencies from the requirements.txt file

      - name: Ensure browsers are installed              # Install Playwright browsers (e.g., Chromium)
        run: |
          python -m playwright install chromium --with-deps     # Install Playwright and required browser dependencies

      - name: Run tests                                   # Run the tests using pytest
        run: |
          pytest -v -s                                    # Run pytest in verbose mode to get detailed output of the test results
