name: Tests

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright
          pip install allure-pytest

      - name: Ensure browsers are installed
        run: python -m playwright install chromium --with-deps

      - name: Run tests
        run:
          pytest -v -s

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
