name: Tests with Allure Report

on:
  - push  # Trigger the workflow when there is a push to the repository

jobs:
  test:
    runs-on: windows-latest  # Run on the latest available Windows environment

    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Setup Python  # Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies  # Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed  # Install Playwright and the required browsers
        run: |
          python -m playwright install chromium --with-deps

      - name: Install Allure Commandline on Windows
        run: |
          # Download the Allure command-line tool zip file
          Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.zip" -OutFile "allure.zip"
          
          # Extract the zip file to the current directory
          Expand-Archive -Path "allure.zip" -DestinationPath "allure"
          
          # Verify the extraction, ensure allure.bat exists
          if (Test-Path "allure\allure-2.32.0\bin\allure.bat") {
              Write-Host "allure.bat found"
          } else {
              Write-Host "allure.bat not found"
              exit 1  # Exit the action if allure.bat is not found
          }

          # Create target directory for Allure if it doesn't exist
          $allurePath = "C:\allure\bin"
          if (-not (Test-Path $allurePath)) {
              New-Item -Path $allurePath -ItemType Directory
          }

          # Move allure.bat to the target directory
          move-item -Path "allure\allure-2.32.0\bin\allure.bat" -Destination $allurePath -Force

          # Ensure allure is in the PATH for the current session (it won't persist across sessions)
          [System.Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$allurePath", [System.EnvironmentVariableTarget]::Process)

      - name: Verify Allure installation
        run: |
          allure --version  # Check if allure is accessible
          allure generate allure-results --clean -o allure-report  # Generate the Allure HTML report

      - name: Upload Allure results as artifacts  # Upload Allure results for use in later steps
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure Report to GitHub Pages  # Deploy the generated report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./allure-report
          github_token: ${{ secrets.GITHUB_TOKEN }}
