name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the code

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      # Step 1: Install Allure Commandline
      - name: Install Allure Commandline
        run: |
          # Download Allure Commandline zip file using curl
          curl -L "https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.zip" -o allure.zip
          
          # Unzip Allure to the current directory
          unzip allure.zip -d allure

          # Move Allure files to C:\allure
          mkdir C:\allure
          Move-Item -Path "allure/allure-2.32.0/bin/*" -Destination "C:\allure\bin" -Force
          
          # Clean up the extracted files
          Remove-Item -Recurse -Force -Path "allure"
          Remove-Item -Force -Path "allure.zip"

      # Step 2: Add Allure to PATH
      - name: Add Allure to PATH
        run: |
          echo "C:\allure\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

      # Step 3: Verify Allure Installation
      - name: Verify Allure Installation
        run: |
          # Ensure Allure is in PATH and check the version
          allure --version

      # Step 4: Run Tests with Allure
      - name: Run Tests with Allure
        run: |
          pytest --alluredir=allure-results

      # Step 5: Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --output allure-report

      # Step 6: Upload Allure Report as Artifact
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

