name: Tests with Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Run on the latest available Windows environment

    steps:
      # Step 1: Checkout code from GitHub repository
      - uses: actions/checkout@v3  # Checkout the code from the repository

      # Step 2: Setup Python environment (Python 3.12.5)
      - name: Setup Python  # Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies  # Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Playwright (needed for running tests)
      - name: Ensure browsers are installed  # Install Playwright and the required browsers
        run: |
          python -m playwright install chromium --with-deps

      - name: Run Tests
        continue-on-error: true
        run: |
          pytest -v

     


