name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      - name: Install Allure Commandline
        run: |
            curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.zip"
            unzip allure.zip -d allure
            sudo mv allure/allure-2.32.0/bin/* /usr/local/bin/
            rm -rf allure allure.zip
            ls /usr/local/bin/  # List files in the bin directory

      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          # Start Allure server from the installed directory
          C:\allure\bin\allure serve allure-results

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-results







#- name: Install Google Chrome
#        run: |
#          # Download Chrome installer
#          $chrome_installer_url = "https://dl.google.com/chrome/install/latest/chrome_installer.exe"
#          Invoke-WebRequest -Uri $chrome_installer_url -OutFile "$env:USERPROFILE\chrome_installer.exe"
#
#          # Install Chrome silently
#          Start-Process -FilePath "$env:USERPROFILE\chrome_installer.exe" -ArgumentList "/silent", "/install" -Wait
#
#          # Clean up installer file
#          Remove-Item "$env:USERPROFILE\chrome_installer.exe"
