name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main  # Or any branch you want to trigger actions from

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.12.5
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      # Run the tests with pytest and generate allure results
      - name: Run pytest
        continue-on-error: true  # Ensure the pipeline continues even if tests fail
        run: |
          pytest --maxfail=1 --disable-warnings -v -s --alluredir=allure-results

      # Generate Allure report (even if tests fail)
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # Upload the generated Allure report as an artifact
      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
