name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      - name: Install Allure Commandline
        run: |
          # Download Allure Commandline zip file using curl
          curl -L "https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.zip" -o allure.zip
          
          # Unzip Allure to the current directory
          unzip allure.zip -d allure

          # Move Allure files to C:\allure
          mkdir C:\allure
          Move-Item -Path "allure/allure-2.32.0/bin/*" -Destination "C:\allure\bin" -Force
          
          # Clean up the extracted files
          Remove-Item -Recurse -Force -Path "allure"
          Remove-Item -Force -Path "allure.zip"

      - name: Add Allure to PATH for current session
        run: |
          $env:PATH = "C:\allure\bin;" + $env:PATH
          echo "Updated PATH: $env:PATH"  # Debugging step to check if path is set correctly.

      - name: Verify Allure Installation
        run: |
          # Check if Allure is in the path
          if ($env:PATH -contains "C:\allure\bin") {
            Write-Host "Allure is in the path."
          } else {
            Write-Host "Allure is NOT in the path."
          }

          # Now check allure version to verify it works
          allure --version  # This should print the Allure version if installed correctly

      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --output allure-report  # Generate the Allure report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
